fix(eslint): check whole function scopes for used variables
otodockal/qwik pull request #1
Opened 2021-10-11 20:46 UTC by luki215

I've noticed your rule is covering just parent qHook/qComponent params,  from the examples Miško provided I think it should consider whole scope. 

AST explorer with scoped variables: 
https://astexplorer.net/#/gist/55f073408c4a5d50f051a2e40830abff/adaeba3d56546020165fd37e74f38e41e025941b

2021-10-11 21:26 UTC, otodockal commented
@luki215 yeah, definitely the whole scope, you're right! thank you.

2021-10-11 21:27 UTC, otodockal approved these changes

2021-10-11 21:43 UTC, otodockal commented
@luki215 just one thing, could you pls update the PR and only rename this part (and related code)?

from:
```js
qHookStore.set(getNodeId(node), {
  params: flattenFnNodeParams(fnNode),
  parentNode: walkToFirstQHook(node.parent),
});
```  

to:
```js
qHookStore.set(getNodeId(node), {
  variables: flattenScopeVariables(fnNode),
  parentNode: walkToFirstQHook(node.parent),
});
```                  

Or something like that. Sorry for this request, but it's no longer about params.

2021-10-11 21:44 UTC, otodockal requested changes
one update pls according to my prev comment, thank you.

2021-10-11 22:05 UTC, luki215 commented
> one update pls according to my prev comment, thank you.

Yeah, I've missed that, thank you! Updated.

2021-10-11 22:19 UTC, otodockal commented on src/eslint/index.js
> +                    params: flattenScopeVariables(fnNode),
@luki215 and last thing, params -> **variables**. thanks. sorry :-D

2021-10-12 07:28 UTC, luki215 commented on src/eslint/index.js
> +                    params: flattenScopeVariables(fnNode),
:D done 👍

2021-10-12 10:28 UTC, merged